version: "3"
services:
  mongodb:
    image: mongo:3.0
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  rest:
    build: ./minihackernewsapi
    ports:
      - "8080:8080"
    links:
      - mongodb
    environment:
     MINIHACKERNEWS_MONGODB_HOST: mongodb